from django.urls import path

from Appblog.views import (
    inicio,
    inicio_seccion,
    cursos,
    articulos,
    sobre_mi,
    subscripcion,
    procesar_formulario,
    formulario_form,
    busqueda_2,
    buscar_2,
    busqueda_autor,
    buscar_autor,
    listas_cursos,
    CursoDetalle,
    CursoCreacion,
    CursoDelete,
    CursoUpdateView,
    CursoList,
    MyLogin,
    MyLogout,
    register,
    editar_perfil,
    agregar_avatar,
)


urlpatterns = [
    path("inicio/", inicio, name="inicio"),
    path("iniciar-seccion/", inicio_seccion, name="inicio-seccion"),
    path("curso/", cursos, name="cursos"),
    path("subscripcion/", subscripcion, name="subscripcion"),
    path("articulos/", articulos, name="articulos"),
    path("about/", sobre_mi, name="about"),
    path("formulario/", procesar_formulario, name="formulario"),
    path("formulario-2/", formulario_form, name="formulario-2"),
    path("busqueda-2/", busqueda_2, name="busqueda-2"),
    path("buscar-2/", buscar_2),
    path("busqueda-autor/", busqueda_autor, name="busqueda-autor"),
    path("buscar-autor/", buscar_autor, name="buscar-autor"),
    path("cursos-lista/", listas_cursos),
    path("curso/list", CursoList.as_view(), name="CursoList"),
    path("r'(?P<pk>\d+)^$'", CursoDetalle.as_view(), name="CursoDetail"),
    path("curso-nuevo/", CursoCreacion.as_view(), name="CursoNew"),
    path("editar/<pk>", CursoUpdateView.as_view(), name="CursoUpdate"),
    path("borrar/<pk>", CursoDelete.as_view(), name="CursoDelete"),
    path("login/", MyLogin.as_view(), name="Login"),
    path("logout/", MyLogout.as_view(), name="Logout"),
    path("register/", register, name="Register"),
    path("editar-perfil/", editar_perfil, name="EditarPerfil"),
    path("agregar-avatar/", agregar_avatar, name="AgregarAvatar"),
    path("", inicio),
]
